image:
  tag: 6.7.3-alpine

service:
  type: NodePort

readinessProbe:
  initialDelaySeconds: 90
  periodSeconds: 60
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 90
  periodSeconds: 60

plugins:
  install:
  - 'https://github.com/SonarQubeCommunity/sonar-pmd/releases/download/2.6/sonar-pmd-plugin-2.6.jar'
  - 'https://github.com/spotbugs/sonar-findbugs/releases/download/3.6.0/sonar-findbugs-plugin-3.6.0.jar'
  - 'https://github.com/checkstyle/sonar-checkstyle/releases/download/4.8/checkstyle-sonar-plugin-4.8.jar'

sonarProperties:
  sonar.forceAuthentication=false
